apiVersion: v1
kind: Service
metadata:
  name: platform-management-service
  namespace: platform-management
  labels:
    app.kubernetes.io/name: platform-management-service
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: platform-management-service
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  sessionAffinity: None
