package org.jrtech.platformmanagement.config

import org.jrtech.platformmanagement.logging.logger
import org.springframework.beans.factory.ObjectProvider
import org.springframework.boot.context.event.ApplicationReadyEvent
import org.springframework.boot.info.BuildProperties
import org.springframework.context.event.EventListener
import org.springframework.stereotype.Component

/**
 * Logs the Maven-stamped build version and timestamp when the application is ready.
 *
 * Values come from [BuildProperties] generated by the spring-boot-maven-plugin
 * `build-info` goal (`META-INF/build-info.properties`). When that file is missing
 * (e.g. IDE run without a Maven package), falls back to "unknown".
 */
@Component
class BuildInfoStartupLogger(
    private val buildProperties: ObjectProvider<BuildProperties>
) {
    private val log = logger()

    @EventListener(ApplicationReadyEvent::class)
    fun onReady() {
        val build = buildProperties.ifAvailable
        val version = build?.version ?: UNKNOWN
        val time = build?.time?.toString() ?: UNKNOWN
        val name = build?.name ?: "platform-management-service"
        log.info(
            "Started {} — build version={}, time={}",
            name,
            version,
            time
        )
    }

    companion object {
        const val UNKNOWN = "unknown"
    }
}
