apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: participant-api

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  # - networkpolicy.yaml   # enable when CNI enforces NetworkPolicy

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: participant-platform

images:
  - name: participant-service-api
    newName: YOUR_ACR_NAME.azurecr.io/participant-service-api
    newTag: "1.0.0"
