apiVersion: v1
kind: Service
metadata:
  name: participant-service-api
  namespace: participant-api
  labels:
    app.kubernetes.io/name: participant-service-api
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: participant-service-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  sessionAffinity: None
